name: "Purge Workflows Runs"
description: "Action to purge workflow runs"
author: "Ludal"
branding:
  icon: trash-2
  color: red
inputs:
  days-old:
    required: false
    description: "Least days the runs have to be old to get purged"
    default: "30"
  ignore-open-pull-requests:
    required: false
    description: "Ignore runs having open pull requests"
    default: "false"
runs:
  using: "node16"
  main: "dist/index.js"
